name: Deploy Build to Build Branch

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Print env + versions (debug)
        run: |
          node -v
          npm -v
          npx vite --version || true
          echo "NODE_ENV=$NODE_ENV"
          echo "CI=$CI"

      - name: Install deps (use lockfile)
        run: npm ci

      - name: Build (force production mode)
        env:
          NODE_ENV: production
        run: npx vite build --mode production

      - name: Assert bundle has no live process.env
        run: |
          if grep -n "process\.env\.NODE_ENV" dist/widgets.min.js; then
            echo "Found process.env.NODE_ENV in widgets.min.js — failing build"
            exit 1
          fi


      - name: Deploy dist to build branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: build
          force_orphan: true
